@url = http://localhost:3000
# @url = https://quraan.onrender.com

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTVhOTQxNWYxMWI4MzdhNGRmYTJlYiIsImVtYWlsIjoiaGFzaGVtQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4ODEzMzkxNiwiZXhwIjoxNjg4NzM4NzE2fQ.iTt0JkYlcrs179TBCUee6oaEIvt3Hd1QejHIc8GVazU
### LOGIN_Student
POST {{url}}/login/student
Content-Type: application/json

{
    "email":"hagar.mohammad.abdelzaher@gmail.com",
    "password":"123456789"
}


### LOGIN_Teacher
POST {{url}}/login/teacher
Content-Type: application/json

{
    "email":"hayahhazem1999@gmail.com",
    "password":"123456789"
}


### LOGIN_Admin
POST {{url}}/login/admin
Content-Type: application/json

{
    "email":"hashem@gmail.com",
    "password":"hahsemhahsem"
}


### REGISTER_Student
POST {{url}}/signUp/student
Content-Type: application/json

{
    "email":"hashem@gmail.com",
    "password":"hahsemhahsem",
    "firstName":"body2",
    "lastName":"ahmed2",
    "DOB":"2015-03-25",
    "gender":"Male"
}


### REGISTER_Teacher
POST {{url}}/signUp/teacher
Content-Type: application/json
Authorization: {{token}}

{
    "email":"hayahhazem1999@gmail.com",
    "password":"123456789",
    "firstName":"Hayah",
    "lastName":"Hazem",
    "DOB":"2015-03-25",
    "gender":"Female"
}
