@url = http://localhost:3000
#@url = https://quraan.onrender.com

 @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OThhMTIxNDNmZDc4ZWI1ZDJjZjNkNiIsImVtYWlsIjoiaGFnYXJAZ21haWwuY29tIiwicm9sZSI6InRlYWNoZXIiLCJpYXQiOjE2ODgzMzE1NjQsImV4cCI6MTY4ODkzNjM2NH0.ENrSsslU2lJPPsHVhGFD8MKRNGLESBwNPjgROAnQgig


### ceate-meeting
GET {{url}}/session/create-meeting/64a1e81a8b3ec8ad5ceeff6f
Content-Type: application/json
Authorization: {{token}}
