@url = http://localhost:3000
#@url = https://quraan.onrender.com

 @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTU4OWJkNDQ2MDA5MzE3ZDMyOTEzMyIsImVtYWlsIjoiYWJkZWxyYWhtYW5AZ21haWwuY29tIiwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE2ODgwNDUxODUsImV4cCI6MTY4ODY0OTk4NX0.X3QkdOSjJAbwq-Tcq1I9t8_MM_GLJJDTl79STB9eoUw

### Get_All_Teacher
get  {{url}}/student/checkout-course/649ccb54e2765eef596e6494
Content-Type: application/json
Authorization: {{token}}

