@url = http://localhost:3000
#@url = https://quraan.onrender.com

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTQ0YTYwNTY0NTkxNGIwYTAzZDYwYiIsImVtYWlsIjoiaGFzaGVtQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NzQ0OTYzNSwiZXhwIjoxNjg4MDU0NDM1fQ.7RCUMAhRopfBJPWCH0pc7eKuvjvOdRGmoylxUrqAPRA

### LOGIN_Student
Get {{url}}/meeting
Content-Type: application/json



### LOGIN_Teacher
POST {{url}}/login/teacher
Content-Type: application/json

{
    "email":"alffi@gmail.com",
    "password":"hahsemhahsem"
}


### LOGIN_Admin
POST {{url}}/login/admin
Content-Type: application/json

{
    "email":"hashem@gmail.com",
    "password":"hahsemhahsem"
}


### REGISTER_Student
POST {{url}}/signUp/student
Content-Type: application/json

{
    "email":"hashem@gmail.com",
    "password":"hahsemhahsem",
    "firstName":"body2",
    "lastName":"ahmed2",
    "DOB":"2015-03-25",
    "gender":"Male"
}


### REGISTER_Teacher
POST {{url}}/signUp/teacher
Content-Type: application/json
Authorization: {{token}}

{
    "email":"alffi@gmail.com",
    "password":"hahsemhahsem",
    "firstName":"body2",
    "lastName":"ahmed2",
    "DOB":"2015-03-25",
    "gender":"Male"
}
